# Use DecapBridge PKCE auth (required)
backend:
  name: git-gateway
  repo: rasspixels/rasspixels.github.io
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/80a8db87-8023-4aa8-b9df-cff9e006139a/pkce
  auth_token_endpoint: /sites/80a8db87-8023-4aa8-b9df-cff9e006139a/token
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://rasspixels.github.io

# Dossiers pour stocker tes images sur GitHub
media_folder: "images/uploads"
public_folder: "/images/uploads"

# On enregistre tous les projets dans un seul fichier JSON pour que notre code HTML puisse le lire facilement
collections:
  - name: "data"
    label: "Données du Site"
    files:
      - file: "_data/projects.json"
        name: "projects"
        label: "Liste des Projets"
        fields:
          - name: "projects_list"
            label: "Projets"
            widget: "list"
            fields:
              - {label: "Titre du projet", name: "title", widget: "string"}
              - {label: "Catégorie", name: "category", widget: "select", options: ["logo", "poster", "banner", "illustration", "3d", "animation"]}
              - {label: "Image ou Thumbnail", name: "image", widget: "image", required: false}
              - {label: "Lien de la vidéo YouTube (si animation)", name: "youtube_link", widget: "string", required: false}
              - {label: "Description", name: "body", widget: "markdown", required: false}
